const languages = ['eng', 'рус'] as const;

type Language = (typeof languages)[number];

const text = {
  eng: {
    analyze: 'AI is reading...',
    authChoiceText: 'Create account to save your progress.',
    authChoiceTitle: 'Your personal reboot is ready',
    back: '← Back',
    brainCondition: 'Brain condition',
    checkIn: 'Daily check-in',
    focus: 'Focus',
    health: 'Synap Index',
    homeTitle: 'In a Fog',
    journal: 'State journal',
    landingEyebrow: 'Neuro reboot protocol',
    landingTitle: "Your brain is not broken. It's just overloaded.",
    landingText: 'Based on your sleep, screen time & daily check-in.',
    login: 'Log in',
    logout: 'Log out',
    mode: 'Mode',
    myBrain: 'My Brain',
    pfc: 'Prefrontal cortex (PFC)',
    science: 'Science',
    screenshot: 'Upload your screenshot',
    signup: 'Sign up',
    start: 'Start reboot',
    tracker: 'Tracker',
    training: 'Training',
    weakZone: 'Vulnerable zone',
  },
  рус: {
    analyze: 'ИИ читает...',
    authChoiceText: 'Создай аккаунт, чтобы сохранить прогресс.',
    authChoiceTitle: 'Твой личный reboot готов',
    back: '← Назад',
    brainCondition: 'Состояние мозга',
    checkIn: 'Daily check-in',
    focus: 'Фокус',
    health: 'Synap Index',
    homeTitle: 'В тумане',
    journal: 'Дневник состояния',
    landingEyebrow: 'Протокол нейро-перезагрузки',
    landingTitle: 'Твой мозг не сломан. Он просто перегружен.',
    landingText: 'На основе сна, экранного времени и daily check-in.',
    login: 'Войти',
    logout: 'Выйти',
    mode: 'Режим',
    myBrain: 'Мой мозг',
    pfc: 'Префронтальная кора',
    science: 'Наука',
    screenshot: 'Загрузить скриншот',
    signup: 'Регистрация',
    start: 'Start reboot',
    tracker: 'Трекер',
    training: 'Задания',
    weakZone: 'Уязвимая зона',
  },
} satisfies Record<Language, Record<string, string>>;

export { languages, text };
export type { Language };
